# Form implementation generated from reading ui file '.\ui\main.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 581)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1011, 551))
        self.stackedWidget.setBaseSize(QtCore.QSize(0, 0))
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.label_2 = QtWidgets.QLabel(parent=self.home_page)
        self.label_2.setGeometry(QtCore.QRect(290, 140, 431, 221))
        self.label_2.setStyleSheet("font-size: 48px")
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.home_page)
        self.upload_page = QtWidgets.QWidget()
        self.upload_page.setObjectName("upload_page")
        self.widget = QtWidgets.QWidget(parent=self.upload_page)
        self.widget.setGeometry(QtCore.QRect(310, 190, 381, 161))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(70, 10, 241, 41))
        self.label.setStyleSheet("font-size: 28px")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(290, 130, 61, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setGeometry(QtCore.QRect(270, 80, 101, 41))
        self.pushButton.setStyleSheet("\n"
"  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"vertical-align: baseline;\n"
"white-space: nowrap;\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"focus {\n"
"  box-shadow: 0 0 0 4px rgba(0, 149, 255, .15);\n"
"}\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"active {\n"
"  background-color: #0064bd;\n"
"  box-shadow: none;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.widget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 80, 251, 41))
        self.plainTextEdit.setStyleSheet("background-color: \"white\"")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.stackedWidget.addWidget(self.upload_page)
        self.initial_page = QtWidgets.QWidget()
        self.initial_page.setObjectName("initial_page")
        self.label_4 = QtWidgets.QLabel(parent=self.initial_page)
        self.label_4.setGeometry(QtCore.QRect(580, 60, 221, 41))
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.label_4.setToolTipDuration(-3)
        self.label_4.setStyleSheet("font-size: 28px;\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.initial_page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(390, 130, 611, 371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(parent=self.verticalLayoutWidget)
        self.widget_2.setStyleSheet("border-radius: 10px")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout.addWidget(self.widget_2)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(parent=self.initial_page)
        self.stackedWidget_2.setGeometry(QtCore.QRect(20, 80, 351, 451))
        self.stackedWidget_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.stackedWidget_2.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.stackedWidget_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.metric_subwidget = QtWidgets.QWidget()
        self.metric_subwidget.setObjectName("metric_subwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.metric_subwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 150, 175, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.update_calibration_button = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.update_calibration_button.setStyleSheet("\n"
"  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  color: #fff;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  ")
        self.update_calibration_button.setObjectName("update_calibration_button")
        self.verticalLayout_6.addWidget(self.update_calibration_button)
        self.energy_validation_button = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.energy_validation_button.setStyleSheet("\n"
"  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"vertical-align: baseline;\n"
"white-space: nowrap;\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"focus {\n"
"  box-shadow: 0 0 0 4px rgba(0, 149, 255, .15);\n"
"}\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"active {\n"
"  background-color: #0064bd;\n"
"  box-shadow: none;\n"
"}")
        self.energy_validation_button.setObjectName("energy_validation_button")
        self.verticalLayout_6.addWidget(self.energy_validation_button)
        self.stackedWidget_2.addWidget(self.metric_subwidget)
        self.calibration_subwidget = QtWidgets.QWidget()
        self.calibration_subwidget.setObjectName("calibration_subwidget")
        self.label_5 = QtWidgets.QLabel(parent=self.calibration_subwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 30, 171, 51))
        self.label_5.setStyleSheet("font-size: 18px;")
        self.label_5.setObjectName("label_5")
        self.update_button = QtWidgets.QPushButton(parent=self.calibration_subwidget)
        self.update_button.setGeometry(QtCore.QRect(100, 330, 151, 41))
        self.update_button.setStyleSheet("\n"
"  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"vertical-align: baseline;\n"
"white-space: nowrap;\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"focus {\n"
"  box-shadow: 0 0 0 4px rgba(0, 149, 255, .15);\n"
"}\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"active {\n"
"  background-color: #0064bd;\n"
"  box-shadow: none;\n"
"}")
        self.update_button.setObjectName("update_button")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.calibration_subwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 100, 321, 201))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.text_u = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.text_u.setEnabled(False)
        self.text_u.setStyleSheet("background-color: \"white\";")
        self.text_u.setObjectName("text_u")
        self.horizontalLayout_2.addWidget(self.text_u)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.pushButton_10.setStyleSheet("  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"vertical-align: baseline;\n"
"white-space: nowrap;\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"focus {\n"
"  box-shadow: 0 0 0 4px rgba(0, 149, 255, .15);\n"
"}\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"active {\n"
"  background-color: #0064bd;\n"
"  box-shadow: none;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_2.addWidget(self.pushButton_10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.text_th = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.text_th.setEnabled(False)
        self.text_th.setStyleSheet("background-color: \"white\";")
        self.text_th.setObjectName("text_th")
        self.horizontalLayout_6.addWidget(self.text_th)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.pushButton_11.setStyleSheet("\n"
"  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"vertical-align: baseline;\n"
"white-space: nowrap;\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"focus {\n"
"  box-shadow: 0 0 0 4px rgba(0, 149, 255, .15);\n"
"}\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"active {\n"
"  background-color: #0064bd;\n"
"  box-shadow: none;\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_6.addWidget(self.pushButton_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.text_k = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.text_k.setEnabled(False)
        self.text_k.setStyleSheet("background-color: \"white\";")
        self.text_k.setObjectName("text_k")
        self.horizontalLayout_7.addWidget(self.text_k)
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.pushButton_12.setStyleSheet("\n"
"  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"vertical-align: baseline;\n"
"white-space: nowrap;\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"focus {\n"
"  box-shadow: 0 0 0 4px rgba(0, 149, 255, .15);\n"
"}\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"active {\n"
"  background-color: #0064bd;\n"
"  box-shadow: none;\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_7.addWidget(self.pushButton_12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.text_other = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.text_other.setEnabled(False)
        self.text_other.setStyleSheet("background-color: \"white\"")
        self.text_other.setObjectName("text_other")
        self.horizontalLayout_8.addWidget(self.text_other)
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.pushButton_13.setStyleSheet("\n"
"  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"vertical-align: baseline;\n"
"white-space: nowrap;\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"focus {\n"
"  box-shadow: 0 0 0 4px rgba(0, 149, 255, .15);\n"
"}\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"active {\n"
"  background-color: #0064bd;\n"
"  box-shadow: none;\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_8.addWidget(self.pushButton_13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.stackedWidget_2.addWidget(self.calibration_subwidget)
        self.stackedWidget.addWidget(self.initial_page)
        self.profile_page = QtWidgets.QWidget()
        self.profile_page.setObjectName("profile_page")
        self.label_6 = QtWidgets.QLabel(parent=self.profile_page)
        self.label_6.setGeometry(QtCore.QRect(290, 0, 451, 61))
        self.label_6.setStyleSheet("font-size: 36px\n"
"")
        self.label_6.setObjectName("label_6")
        self.groupBox = QtWidgets.QGroupBox(parent=self.profile_page)
        self.groupBox.setGeometry(QtCore.QRect(160, 130, 691, 261))
        self.groupBox.setStyleSheet("font-size: 14px;")
        self.groupBox.setObjectName("groupBox")
        self.widget1 = QtWidgets.QWidget(parent=self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(130, 80, 421, 111))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.profile_1_button = QtWidgets.QPushButton(parent=self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profile_1_button.sizePolicy().hasHeightForWidth())
        self.profile_1_button.setSizePolicy(sizePolicy)
        self.profile_1_button.setStyleSheet("  background-color: #0095ff;\n"
"  border-radius: 3px;\n"
"color: #fff;")
        self.profile_1_button.setObjectName("profile_1_button")
        self.gridLayout.addWidget(self.profile_1_button, 0, 0, 1, 1)
        self.profile_2_button = QtWidgets.QPushButton(parent=self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profile_2_button.sizePolicy().hasHeightForWidth())
        self.profile_2_button.setSizePolicy(sizePolicy)
        self.profile_2_button.setBaseSize(QtCore.QSize(1, 0))
        self.profile_2_button.setStyleSheet("  background-color: #0095ff;\n"
"  border-radius: 3px;\n"
"color: #fff;")
        self.profile_2_button.setObjectName("profile_2_button")
        self.gridLayout.addWidget(self.profile_2_button, 0, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setStyleSheet("  background-color: #0095ff;\n"
"  border-radius: 3px;\n"
"color: #fff;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 0, 2, 1, 1)
        self.stackedWidget.addWidget(self.profile_page)
        self.energy_validation_page = QtWidgets.QWidget()
        self.energy_validation_page.setObjectName("energy_validation_page")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.energy_validation_page)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 460, 161, 41))
        self.pushButton_2.setStyleSheet("\n"
"  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"vertical-align: baseline;\n"
"white-space: nowrap;\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"focus {\n"
"  box-shadow: 0 0 0 4px rgba(0, 149, 255, .15);\n"
"}\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"active {\n"
"  background-color: #0064bd;\n"
"  box-shadow: none;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_11 = QtWidgets.QLabel(parent=self.energy_validation_page)
        self.label_11.setGeometry(QtCore.QRect(310, 0, 411, 61))
        self.label_11.setStyleSheet("font-size: 36px;\n"
"")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.widget2 = QtWidgets.QWidget(parent=self.energy_validation_page)
        self.widget2.setGeometry(QtCore.QRect(20, 190, 971, 231))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.residual_layout = QtWidgets.QVBoxLayout()
        self.residual_layout.setObjectName("residual_layout")
        self.horizontalLayout.addLayout(self.residual_layout)
        self.energyVchannel_layout = QtWidgets.QVBoxLayout()
        self.energyVchannel_layout.setObjectName("energyVchannel_layout")
        self.horizontalLayout.addLayout(self.energyVchannel_layout)
        self.fwhm_layout = QtWidgets.QVBoxLayout()
        self.fwhm_layout.setObjectName("fwhm_layout")
        self.horizontalLayout.addLayout(self.fwhm_layout)
        self.widget3 = QtWidgets.QWidget(parent=self.energy_validation_page)
        self.widget3.setGeometry(QtCore.QRect(50, 120, 901, 51))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_12 = QtWidgets.QLabel(parent=self.widget3)
        self.label_12.setStyleSheet("font-size: 14px;\n"
"")
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.validation_isotope_dropdown = QtWidgets.QComboBox(parent=self.widget3)
        self.validation_isotope_dropdown.setObjectName("validation_isotope_dropdown")
        self.validation_isotope_dropdown.addItem("")
        self.validation_isotope_dropdown.addItem("")
        self.validation_isotope_dropdown.addItem("")
        self.validation_isotope_dropdown.addItem("")
        self.validation_isotope_dropdown.addItem("")
        self.validation_isotope_dropdown.addItem("")
        self.validation_isotope_dropdown.addItem("")
        self.validation_isotope_dropdown.addItem("")
        self.validation_isotope_dropdown.addItem("")
        self.horizontalLayout_4.addWidget(self.validation_isotope_dropdown)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.analyze_button = QtWidgets.QPushButton(parent=self.widget3)
        self.analyze_button.setStyleSheet("\n"
"  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"vertical-align: baseline;\n"
"white-space: nowrap;\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"focus {\n"
"  box-shadow: 0 0 0 4px rgba(0, 149, 255, .15);\n"
"}\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"active {\n"
"  background-color: #0064bd;\n"
"  box-shadow: none;\n"
"}")
        self.analyze_button.setObjectName("analyze_button")
        self.horizontalLayout_4.addWidget(self.analyze_button)
        self.add_peak_button = QtWidgets.QPushButton(parent=self.widget3)
        self.add_peak_button.setStyleSheet("\n"
"  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"vertical-align: baseline;\n"
"white-space: nowrap;\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"focus {\n"
"  box-shadow: 0 0 0 4px rgba(0, 149, 255, .15);\n"
"}\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"active {\n"
"  background-color: #0064bd;\n"
"  box-shadow: none;\n"
"}")
        self.add_peak_button.setObjectName("add_peak_button")
        self.horizontalLayout_4.addWidget(self.add_peak_button)
        self.del_peak_button = QtWidgets.QPushButton(parent=self.widget3)
        self.del_peak_button.setStyleSheet("\n"
"  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"vertical-align: baseline;\n"
"white-space: nowrap;\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"focus {\n"
"  box-shadow: 0 0 0 4px rgba(0, 149, 255, .15);\n"
"}\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"active {\n"
"  background-color: #0064bd;\n"
"  box-shadow: none;\n"
"}")
        self.del_peak_button.setObjectName("del_peak_button")
        self.horizontalLayout_4.addWidget(self.del_peak_button)
        self.stackedWidget.addWidget(self.energy_validation_page)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1013, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuOpen = QtWidgets.QMenu(parent=self.menuBar)
        self.menuOpen.setObjectName("menuOpen")
        self.menuChart_Design = QtWidgets.QMenu(parent=self.menuBar)
        self.menuChart_Design.setEnabled(False)
        self.menuChart_Design.setObjectName("menuChart_Design")
        self.menuCalibration = QtWidgets.QMenu(parent=self.menuBar)
        self.menuCalibration.setEnabled(False)
        self.menuCalibration.setObjectName("menuCalibration")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtGui.QAction(parent=MainWindow)
        self.actionOpen.setCheckable(False)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(parent=MainWindow)
        self.actionSave.setEnabled(False)
        self.actionSave.setObjectName("actionSave")
        self.actionPrint = QtGui.QAction(parent=MainWindow)
        self.actionPrint.setEnabled(False)
        self.actionPrint.setObjectName("actionPrint")
        self.actionClose = QtGui.QAction(parent=MainWindow)
        self.actionClose.setEnabled(False)
        self.actionClose.setObjectName("actionClose")
        self.actionSettings = QtGui.QAction(parent=MainWindow)
        self.actionSettings.setEnabled(True)
        self.actionSettings.setObjectName("actionSettings")
        self.actionReset = QtGui.QAction(parent=MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionRun = QtGui.QAction(parent=MainWindow)
        self.actionRun.setEnabled(True)
        self.actionRun.setObjectName("actionRun")
        self.menuOpen.addAction(self.actionOpen)
        self.menuOpen.addAction(self.actionSave)
        self.menuOpen.addAction(self.actionPrint)
        self.menuOpen.addAction(self.actionClose)
        self.menuChart_Design.addAction(self.actionSettings)
        self.menuChart_Design.addAction(self.actionReset)
        self.menuCalibration.addAction(self.actionRun)
        self.menuBar.addAction(self.menuOpen.menuAction())
        self.menuBar.addAction(self.menuChart_Design.menuAction())
        self.menuBar.addAction(self.menuCalibration.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Welcome to Gamma"))
        self.label.setText(_translate("MainWindow", "Upload Sample file"))
        self.label_3.setText(_translate("MainWindow", "(.CNF File)"))
        self.pushButton.setText(_translate("MainWindow", "Browse"))
        self.label_4.setText(_translate("MainWindow", "Initial Metrics"))
        self.update_calibration_button.setText(_translate("MainWindow", "Update Initial Calibration"))
        self.energy_validation_button.setText(_translate("MainWindow", "Energy Validation"))
        self.label_5.setText(_translate("MainWindow", "Calibration Dataset"))
        self.update_button.setText(_translate("MainWindow", "Update"))
        self.label_7.setText(_translate("MainWindow", "IAEA-U:          "))
        self.pushButton_10.setText(_translate("MainWindow", "Browse.."))
        self.label_8.setText(_translate("MainWindow", "IAEA-Th:         "))
        self.pushButton_11.setText(_translate("MainWindow", "Browse.."))
        self.label_9.setText(_translate("MainWindow", "IAEA-K:           "))
        self.pushButton_12.setText(_translate("MainWindow", "Browse.."))
        self.label_10.setText(_translate("MainWindow", "Other:             "))
        self.pushButton_13.setText(_translate("MainWindow", "Browse.."))
        self.label_6.setText(_translate("MainWindow", "Choose a profile to validate:"))
        self.groupBox.setTitle(_translate("MainWindow", "Each Profile contains a set of peaks of interest to be calibrated against"))
        self.profile_1_button.setText(_translate("MainWindow", "Profile 1"))
        self.profile_2_button.setText(_translate("MainWindow", "Profile 2"))
        self.pushButton_7.setText(_translate("MainWindow", "Add.."))
        self.pushButton_2.setText(_translate("MainWindow", "Optimize Coefficients"))
        self.label_11.setText(_translate("MainWindow", "Energy Validation Control"))
        self.label_12.setText(_translate("MainWindow", "Isotope:"))
        self.validation_isotope_dropdown.setItemText(0, _translate("MainWindow", "Choose.."))
        self.validation_isotope_dropdown.setItemText(1, _translate("MainWindow", "Pb-210 (46.539 keV)"))
        self.validation_isotope_dropdown.setItemText(2, _translate("MainWindow", "Pb-212 (238.632 keV)"))
        self.validation_isotope_dropdown.setItemText(3, _translate("MainWindow", "Pb-214 (295.2228 keV)"))
        self.validation_isotope_dropdown.setItemText(4, _translate("MainWindow", "Ac-228 (338.32 keV)"))
        self.validation_isotope_dropdown.setItemText(5, _translate("MainWindow", "Pb-214 (351.9321 keV)"))
        self.validation_isotope_dropdown.setItemText(6, _translate("MainWindow", "Bi-214 (609.32 keV)"))
        self.validation_isotope_dropdown.setItemText(7, _translate("MainWindow", "Ac-228 (911.204 keV)"))
        self.validation_isotope_dropdown.setItemText(8, _translate("MainWindow", "K-40 (1460.83 keV)"))
        self.analyze_button.setText(_translate("MainWindow", "Analyze"))
        self.add_peak_button.setText(_translate("MainWindow", "Add Peak"))
        self.del_peak_button.setText(_translate("MainWindow", "Delete Peak"))
        self.menuOpen.setTitle(_translate("MainWindow", "File"))
        self.menuChart_Design.setTitle(_translate("MainWindow", "Chart Design"))
        self.menuCalibration.setTitle(_translate("MainWindow", "Calibration"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionRun.setText(_translate("MainWindow", "Run"))
