# Form implementation generated from reading ui file '.\ui\main.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 581)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1011, 551))
        self.stackedWidget.setBaseSize(QtCore.QSize(0, 0))
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.label_2 = QtWidgets.QLabel(parent=self.home_page)
        self.label_2.setGeometry(QtCore.QRect(290, 140, 431, 221))
        self.label_2.setStyleSheet("font-size: 48px")
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.home_page)
        self.upload_page = QtWidgets.QWidget()
        self.upload_page.setObjectName("upload_page")
        self.widget = QtWidgets.QWidget(parent=self.upload_page)
        self.widget.setGeometry(QtCore.QRect(310, 190, 381, 161))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(70, 10, 241, 41))
        self.label.setStyleSheet("font-size: 28px")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(290, 130, 61, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setGeometry(QtCore.QRect(270, 80, 101, 41))
        self.pushButton.setStyleSheet("\n"
"  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"vertical-align: baseline;\n"
"white-space: nowrap;\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"focus {\n"
"  box-shadow: 0 0 0 4px rgba(0, 149, 255, .15);\n"
"}\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"active {\n"
"  background-color: #0064bd;\n"
"  box-shadow: none;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.widget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 80, 251, 41))
        self.plainTextEdit.setStyleSheet("background-color: \"white\"")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.stackedWidget.addWidget(self.upload_page)
        self.initial_page = QtWidgets.QWidget()
        self.initial_page.setObjectName("initial_page")
        self.label_4 = QtWidgets.QLabel(parent=self.initial_page)
        self.label_4.setGeometry(QtCore.QRect(580, 60, 221, 41))
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.label_4.setToolTipDuration(-3)
        self.label_4.setStyleSheet("font-size: 28px;\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.initial_page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(390, 130, 611, 371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(parent=self.verticalLayoutWidget)
        self.widget_2.setStyleSheet("border-radius: 10px")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout.addWidget(self.widget_2)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(parent=self.initial_page)
        self.stackedWidget_2.setGeometry(QtCore.QRect(20, 80, 351, 451))
        self.stackedWidget_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.stackedWidget_2.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.stackedWidget_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.metric_subwidget = QtWidgets.QWidget()
        self.metric_subwidget.setObjectName("metric_subwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.metric_subwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 150, 175, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.update_calibration_button = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.update_calibration_button.setStyleSheet("\n"
"  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  color: #fff;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  ")
        self.update_calibration_button.setObjectName("update_calibration_button")
        self.verticalLayout_6.addWidget(self.update_calibration_button)
        self.energy_validation_button = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.energy_validation_button.setStyleSheet("\n"
"  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"vertical-align: baseline;\n"
"white-space: nowrap;\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"focus {\n"
"  box-shadow: 0 0 0 4px rgba(0, 149, 255, .15);\n"
"}\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"active {\n"
"  background-color: #0064bd;\n"
"  box-shadow: none;\n"
"}")
        self.energy_validation_button.setObjectName("energy_validation_button")
        self.verticalLayout_6.addWidget(self.energy_validation_button)
        self.stackedWidget_2.addWidget(self.metric_subwidget)
        self.calibration_subwidget = QtWidgets.QWidget()
        self.calibration_subwidget.setObjectName("calibration_subwidget")
        self.label_5 = QtWidgets.QLabel(parent=self.calibration_subwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 30, 171, 51))
        self.label_5.setStyleSheet("font-size: 18px;")
        self.label_5.setObjectName("label_5")
        self.update_button = QtWidgets.QPushButton(parent=self.calibration_subwidget)
        self.update_button.setGeometry(QtCore.QRect(100, 330, 151, 41))
        self.update_button.setStyleSheet("\n"
"  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"vertical-align: baseline;\n"
"white-space: nowrap;\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"focus {\n"
"  box-shadow: 0 0 0 4px rgba(0, 149, 255, .15);\n"
"}\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"active {\n"
"  background-color: #0064bd;\n"
"  box-shadow: none;\n"
"}")
        self.update_button.setObjectName("update_button")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.calibration_subwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 100, 321, 201))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.text_u = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.text_u.setEnabled(False)
        self.text_u.setStyleSheet("background-color: \"white\";")
        self.text_u.setObjectName("text_u")
        self.horizontalLayout_2.addWidget(self.text_u)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.pushButton_10.setStyleSheet("  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"vertical-align: baseline;\n"
"white-space: nowrap;\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"focus {\n"
"  box-shadow: 0 0 0 4px rgba(0, 149, 255, .15);\n"
"}\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"active {\n"
"  background-color: #0064bd;\n"
"  box-shadow: none;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_2.addWidget(self.pushButton_10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.text_th = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.text_th.setEnabled(False)
        self.text_th.setStyleSheet("background-color: \"white\";")
        self.text_th.setObjectName("text_th")
        self.horizontalLayout_6.addWidget(self.text_th)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.pushButton_11.setStyleSheet("\n"
"  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"vertical-align: baseline;\n"
"white-space: nowrap;\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"focus {\n"
"  box-shadow: 0 0 0 4px rgba(0, 149, 255, .15);\n"
"}\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"active {\n"
"  background-color: #0064bd;\n"
"  box-shadow: none;\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_6.addWidget(self.pushButton_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.text_k = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.text_k.setEnabled(False)
        self.text_k.setStyleSheet("background-color: \"white\";")
        self.text_k.setObjectName("text_k")
        self.horizontalLayout_7.addWidget(self.text_k)
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.pushButton_12.setStyleSheet("\n"
"  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"vertical-align: baseline;\n"
"white-space: nowrap;\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"focus {\n"
"  box-shadow: 0 0 0 4px rgba(0, 149, 255, .15);\n"
"}\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"active {\n"
"  background-color: #0064bd;\n"
"  box-shadow: none;\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_7.addWidget(self.pushButton_12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.text_other = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.text_other.setEnabled(False)
        self.text_other.setStyleSheet("background-color: \"white\"")
        self.text_other.setObjectName("text_other")
        self.horizontalLayout_8.addWidget(self.text_other)
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.pushButton_13.setStyleSheet("\n"
"  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"vertical-align: baseline;\n"
"white-space: nowrap;\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"focus {\n"
"  box-shadow: 0 0 0 4px rgba(0, 149, 255, .15);\n"
"}\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"active {\n"
"  background-color: #0064bd;\n"
"  box-shadow: none;\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_8.addWidget(self.pushButton_13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.stackedWidget_2.addWidget(self.calibration_subwidget)
        self.stackedWidget.addWidget(self.initial_page)
        self.profile_page = QtWidgets.QWidget()
        self.profile_page.setObjectName("profile_page")
        self.label_6 = QtWidgets.QLabel(parent=self.profile_page)
        self.label_6.setGeometry(QtCore.QRect(290, 0, 451, 61))
        self.label_6.setStyleSheet("font-size: 36px\n"
"")
        self.label_6.setObjectName("label_6")
        self.groupBox = QtWidgets.QGroupBox(parent=self.profile_page)
        self.groupBox.setGeometry(QtCore.QRect(160, 130, 691, 261))
        self.groupBox.setStyleSheet("font-size: 14px;")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget2 = QtWidgets.QWidget(parent=self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(130, 80, 421, 111))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setStyleSheet("  background-color: #0095ff;\n"
"  border-radius: 3px;\n"
"color: #fff;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.profile_page)
        self.energy_validation_page = QtWidgets.QWidget()
        self.energy_validation_page.setObjectName("energy_validation_page")
        self.label_11 = QtWidgets.QLabel(parent=self.energy_validation_page)
        self.label_11.setGeometry(QtCore.QRect(310, 0, 411, 61))
        self.label_11.setStyleSheet("font-size: 36px;\n"
"")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.layoutWidget3 = QtWidgets.QWidget(parent=self.energy_validation_page)
        self.layoutWidget3.setGeometry(QtCore.QRect(50, 120, 901, 51))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_12 = QtWidgets.QLabel(parent=self.layoutWidget3)
        self.label_12.setStyleSheet("font-size: 14px;\n"
"")
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.validation_isotope_dropdown = QtWidgets.QComboBox(parent=self.layoutWidget3)
        self.validation_isotope_dropdown.setObjectName("validation_isotope_dropdown")
        self.validation_isotope_dropdown.addItem("")
        self.horizontalLayout_4.addWidget(self.validation_isotope_dropdown)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.analyze_button = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.analyze_button.setStyleSheet("\n"
"  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"vertical-align: baseline;\n"
"white-space: nowrap;\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"focus {\n"
"  box-shadow: 0 0 0 4px rgba(0, 149, 255, .15);\n"
"}\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"active {\n"
"  background-color: #0064bd;\n"
"  box-shadow: none;\n"
"}")
        self.analyze_button.setObjectName("analyze_button")
        self.horizontalLayout_4.addWidget(self.analyze_button)
        self.del_peak_button = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.del_peak_button.setStyleSheet("\n"
"  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"vertical-align: baseline;\n"
"white-space: nowrap;\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"focus {\n"
"  box-shadow: 0 0 0 4px rgba(0, 149, 255, .15);\n"
"}\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"active {\n"
"  background-color: #0064bd;\n"
"  box-shadow: none;\n"
"}")
        self.del_peak_button.setObjectName("del_peak_button")
        self.horizontalLayout_4.addWidget(self.del_peak_button)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.energy_validation_page)
        self.tabWidget.setGeometry(QtCore.QRect(10, 180, 991, 371))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget4 = QtWidgets.QWidget(parent=self.tab)
        self.layoutWidget4.setGeometry(QtCore.QRect(0, 10, 981, 271))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.residual_layout = QtWidgets.QVBoxLayout()
        self.residual_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.residual_layout.setObjectName("residual_layout")
        self.horizontalLayout_14.addLayout(self.residual_layout)
        self.fwhm_layout = QtWidgets.QVBoxLayout()
        self.fwhm_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.fwhm_layout.setObjectName("fwhm_layout")
        self.horizontalLayout_14.addLayout(self.fwhm_layout)
        self.energyVchannel_layout = QtWidgets.QVBoxLayout()
        self.energyVchannel_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.energyVchannel_layout.setObjectName("energyVchannel_layout")
        self.horizontalLayout_14.addLayout(self.energyVchannel_layout)
        self.save_profile_button = QtWidgets.QPushButton(parent=self.tab)
        self.save_profile_button.setGeometry(QtCore.QRect(420, 290, 151, 41))
        self.save_profile_button.setStyleSheet("\n"
"  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"vertical-align: baseline;\n"
"white-space: nowrap;\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"focus {\n"
"  box-shadow: 0 0 0 4px rgba(0, 149, 255, .15);\n"
"}\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"active {\n"
"  background-color: #0064bd;\n"
"  box-shadow: none;\n"
"}")
        self.save_profile_button.setObjectName("save_profile_button")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.add_peak_button = QtWidgets.QPushButton(parent=self.tab_2)
        self.add_peak_button.setGeometry(QtCore.QRect(390, 280, 171, 41))
        self.add_peak_button.setStyleSheet("\n"
"  background-color: #0095ff;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",\"Liberation Sans\",sans-serif;\n"
"  font-size: 13px;\n"
"  font-weight: 400;\n"
"  line-height: 1.15385;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 8px .8em;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"vertical-align: baseline;\n"
"white-space: nowrap;\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"focus {\n"
"  box-shadow: 0 0 0 4px rgba(0, 149, 255, .15);\n"
"}\n"
"\n"
"hover {\n"
"  background-color: #07c;\n"
"}\n"
"\n"
"active {\n"
"  background-color: #0064bd;\n"
"  box-shadow: none;\n"
"}")
        self.add_peak_button.setObjectName("add_peak_button")
        self.widget1 = QtWidgets.QWidget(parent=self.tab_2)
        self.widget1.setGeometry(QtCore.QRect(360, 10, 241, 257))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_17 = QtWidgets.QLabel(parent=self.widget1)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_9.addWidget(self.label_17)
        self.isotope_name = QtWidgets.QLineEdit(parent=self.widget1)
        self.isotope_name.setObjectName("isotope_name")
        self.horizontalLayout_9.addWidget(self.isotope_name)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_18 = QtWidgets.QLabel(parent=self.widget1)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_12.addWidget(self.label_18)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.energy_value = QtWidgets.QLineEdit(parent=self.widget1)
        self.energy_value.setObjectName("energy_value")
        self.horizontalLayout_12.addWidget(self.energy_value)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_25 = QtWidgets.QLabel(parent=self.widget1)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_18.addWidget(self.label_25)
        self.he_rpic_left = QtWidgets.QLineEdit(parent=self.widget1)
        self.he_rpic_left.setObjectName("he_rpic_left")
        self.horizontalLayout_18.addWidget(self.he_rpic_left)
        self.he_rpic_right = QtWidgets.QLineEdit(parent=self.widget1)
        self.he_rpic_right.setObjectName("he_rpic_right")
        self.horizontalLayout_18.addWidget(self.he_rpic_right)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_26 = QtWidgets.QLabel(parent=self.widget1)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_19.addWidget(self.label_26)
        self.be_rpic_left = QtWidgets.QLineEdit(parent=self.widget1)
        self.be_rpic_left.setText("")
        self.be_rpic_left.setObjectName("be_rpic_left")
        self.horizontalLayout_19.addWidget(self.be_rpic_left)
        self.be_rpic_right = QtWidgets.QLineEdit(parent=self.widget1)
        self.be_rpic_right.setText("")
        self.be_rpic_right.setObjectName("be_rpic_right")
        self.horizontalLayout_19.addWidget(self.be_rpic_right)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_27 = QtWidgets.QLabel(parent=self.widget1)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_22.addWidget(self.label_27)
        self.nb_canaux_bfbe = QtWidgets.QLineEdit(parent=self.widget1)
        self.nb_canaux_bfbe.setObjectName("nb_canaux_bfbe")
        self.horizontalLayout_22.addWidget(self.nb_canaux_bfbe)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_28 = QtWidgets.QLabel(parent=self.widget1)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_23.addWidget(self.label_28)
        self.nb_canaux_bfhe = QtWidgets.QLineEdit(parent=self.widget1)
        self.nb_canaux_bfhe.setObjectName("nb_canaux_bfhe")
        self.horizontalLayout_23.addWidget(self.nb_canaux_bfhe)
        self.verticalLayout_7.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_29 = QtWidgets.QLabel(parent=self.widget1)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_24.addWidget(self.label_29)
        self.larger_region_peak = QtWidgets.QLineEdit(parent=self.widget1)
        self.larger_region_peak.setText("")
        self.larger_region_peak.setObjectName("larger_region_peak")
        self.horizontalLayout_24.addWidget(self.larger_region_peak)
        self.verticalLayout_7.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_31 = QtWidgets.QLabel(parent=self.widget1)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_26.addWidget(self.label_31)
        self.reference_width = QtWidgets.QLineEdit(parent=self.widget1)
        self.reference_width.setText("")
        self.reference_width.setObjectName("reference_width")
        self.horizontalLayout_26.addWidget(self.reference_width)
        self.verticalLayout_7.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_30 = QtWidgets.QLabel(parent=self.widget1)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_25.addWidget(self.label_30)
        self.range_value = QtWidgets.QLineEdit(parent=self.widget1)
        self.range_value.setText("")
        self.range_value.setObjectName("range_value")
        self.horizontalLayout_25.addWidget(self.range_value)
        self.verticalLayout_7.addLayout(self.horizontalLayout_25)
        self.tabWidget.addTab(self.tab_2, "")
        self.stackedWidget.addWidget(self.energy_validation_page)
        self.peak_analysis_page = QtWidgets.QWidget()
        self.peak_analysis_page.setObjectName("peak_analysis_page")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.peak_analysis_page)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(50, 40, 461, 301))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.back = QtWidgets.QPushButton(parent=self.peak_analysis_page)
        self.back.setGeometry(QtCore.QRect(50, 10, 75, 24))
        self.back.setObjectName("back")
        self.layoutWidget5 = QtWidgets.QWidget(parent=self.peak_analysis_page)
        self.layoutWidget5.setGeometry(QtCore.QRect(40, 350, 941, 181))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.layoutWidget5)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget6 = QtWidgets.QWidget(parent=self.groupBox_2)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 30, 191, 131))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_13 = QtWidgets.QLabel(parent=self.layoutWidget6)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.total_hits_bfbe = QtWidgets.QLabel(parent=self.layoutWidget6)
        self.total_hits_bfbe.setObjectName("total_hits_bfbe")
        self.horizontalLayout_3.addWidget(self.total_hits_bfbe)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_15 = QtWidgets.QLabel(parent=self.layoutWidget6)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.hits_per_channel_bfbe = QtWidgets.QLabel(parent=self.layoutWidget6)
        self.hits_per_channel_bfbe.setObjectName("hits_per_channel_bfbe")
        self.horizontalLayout_5.addWidget(self.hits_per_channel_bfbe)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.layoutWidget5)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget_5 = QtWidgets.QWidget(parent=self.groupBox_3)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 30, 191, 131))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_19 = QtWidgets.QLabel(parent=self.layoutWidget_5)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_10.addWidget(self.label_19)
        self.total_hits_bfhe = QtWidgets.QLabel(parent=self.layoutWidget_5)
        self.total_hits_bfhe.setObjectName("total_hits_bfhe")
        self.horizontalLayout_10.addWidget(self.total_hits_bfhe)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_21 = QtWidgets.QLabel(parent=self.layoutWidget_5)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_11.addWidget(self.label_21)
        self.hits_per_channel_bfhe = QtWidgets.QLabel(parent=self.layoutWidget_5)
        self.hits_per_channel_bfhe.setObjectName("hits_per_channel_bfhe")
        self.horizontalLayout_11.addWidget(self.hits_per_channel_bfhe)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.layoutWidget5)
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget_6 = QtWidgets.QWidget(parent=self.groupBox_4)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 30, 191, 131))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_14 = QtWidgets.QLabel(parent=self.layoutWidget_6)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_16.addWidget(self.label_14)
        self.total_hits_roi = QtWidgets.QLabel(parent=self.layoutWidget_6)
        self.total_hits_roi.setObjectName("total_hits_roi")
        self.horizontalLayout_16.addWidget(self.total_hits_roi)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_16 = QtWidgets.QLabel(parent=self.layoutWidget_6)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_17.addWidget(self.label_16)
        self.num_channels_peak = QtWidgets.QLabel(parent=self.layoutWidget_6)
        self.num_channels_peak.setObjectName("num_channels_peak")
        self.horizontalLayout_17.addWidget(self.num_channels_peak)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.layoutWidget5)
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget_8 = QtWidgets.QWidget(parent=self.groupBox_5)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 30, 191, 131))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_22 = QtWidgets.QLabel(parent=self.layoutWidget_8)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_20.addWidget(self.label_22)
        self.total_hits_pic = QtWidgets.QLabel(parent=self.layoutWidget_8)
        self.total_hits_pic.setObjectName("total_hits_pic")
        self.horizontalLayout_20.addWidget(self.total_hits_pic)
        self.verticalLayout_9.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_24 = QtWidgets.QLabel(parent=self.layoutWidget_8)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_21.addWidget(self.label_24)
        self.num_channels_peak_2 = QtWidgets.QLabel(parent=self.layoutWidget_8)
        self.num_channels_peak_2.setObjectName("num_channels_peak_2")
        self.horizontalLayout_21.addWidget(self.num_channels_peak_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_21)
        self.horizontalLayout.addWidget(self.groupBox_5)
        self.layoutWidget7 = QtWidgets.QWidget(parent=self.peak_analysis_page)
        self.layoutWidget7.setGeometry(QtCore.QRect(620, 90, 261, 151))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget7)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_37 = QtWidgets.QLabel(parent=self.layoutWidget7)
        self.label_37.setObjectName("label_37")
        self.gridLayout_2.addWidget(self.label_37, 2, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(parent=self.layoutWidget7)
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 1, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(parent=self.layoutWidget7)
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 0, 0, 1, 1)
        self.fwhm = QtWidgets.QLabel(parent=self.layoutWidget7)
        self.fwhm.setObjectName("fwhm")
        self.gridLayout_2.addWidget(self.fwhm, 2, 1, 1, 1)
        self.channel_peak = QtWidgets.QLabel(parent=self.layoutWidget7)
        self.channel_peak.setObjectName("channel_peak")
        self.gridLayout_2.addWidget(self.channel_peak, 0, 1, 1, 1)
        self.energy_peak = QtWidgets.QLabel(parent=self.layoutWidget7)
        self.energy_peak.setObjectName("energy_peak")
        self.gridLayout_2.addWidget(self.energy_peak, 1, 1, 1, 1)
        self.layoutWidget8 = QtWidgets.QWidget(parent=self.peak_analysis_page)
        self.layoutWidget8.setGeometry(QtCore.QRect(350, 10, 158, 26))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pa_prev = QtWidgets.QPushButton(parent=self.layoutWidget8)
        self.pa_prev.setObjectName("pa_prev")
        self.horizontalLayout_13.addWidget(self.pa_prev)
        self.pa_next = QtWidgets.QPushButton(parent=self.layoutWidget8)
        self.pa_next.setObjectName("pa_next")
        self.horizontalLayout_13.addWidget(self.pa_next)
        self.stackedWidget.addWidget(self.peak_analysis_page)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1013, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuOpen = QtWidgets.QMenu(parent=self.menuBar)
        self.menuOpen.setObjectName("menuOpen")
        self.menuChart_Design = QtWidgets.QMenu(parent=self.menuBar)
        self.menuChart_Design.setEnabled(False)
        self.menuChart_Design.setObjectName("menuChart_Design")
        self.menuCalibration = QtWidgets.QMenu(parent=self.menuBar)
        self.menuCalibration.setEnabled(False)
        self.menuCalibration.setObjectName("menuCalibration")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtGui.QAction(parent=MainWindow)
        self.actionOpen.setCheckable(False)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(parent=MainWindow)
        self.actionSave.setEnabled(False)
        self.actionSave.setObjectName("actionSave")
        self.actionPrint = QtGui.QAction(parent=MainWindow)
        self.actionPrint.setEnabled(False)
        self.actionPrint.setObjectName("actionPrint")
        self.actionClose = QtGui.QAction(parent=MainWindow)
        self.actionClose.setEnabled(False)
        self.actionClose.setObjectName("actionClose")
        self.actionSettings = QtGui.QAction(parent=MainWindow)
        self.actionSettings.setEnabled(True)
        self.actionSettings.setObjectName("actionSettings")
        self.actionReset = QtGui.QAction(parent=MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionRun = QtGui.QAction(parent=MainWindow)
        self.actionRun.setEnabled(True)
        self.actionRun.setObjectName("actionRun")
        self.menuOpen.addAction(self.actionOpen)
        self.menuOpen.addAction(self.actionSave)
        self.menuOpen.addAction(self.actionPrint)
        self.menuOpen.addAction(self.actionClose)
        self.menuChart_Design.addAction(self.actionSettings)
        self.menuChart_Design.addAction(self.actionReset)
        self.menuCalibration.addAction(self.actionRun)
        self.menuBar.addAction(self.menuOpen.menuAction())
        self.menuBar.addAction(self.menuChart_Design.menuAction())
        self.menuBar.addAction(self.menuCalibration.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Welcome to Gamma"))
        self.label.setText(_translate("MainWindow", "Upload Sample file"))
        self.label_3.setText(_translate("MainWindow", "(.CNF File)"))
        self.pushButton.setText(_translate("MainWindow", "Browse"))
        self.label_4.setText(_translate("MainWindow", "Initial Metrics"))
        self.update_calibration_button.setText(_translate("MainWindow", "Update Initial Calibration"))
        self.energy_validation_button.setText(_translate("MainWindow", "Energy Validation"))
        self.label_5.setText(_translate("MainWindow", "Calibration Dataset"))
        self.update_button.setText(_translate("MainWindow", "Update"))
        self.label_7.setText(_translate("MainWindow", "IAEA-U:          "))
        self.pushButton_10.setText(_translate("MainWindow", "Browse.."))
        self.label_8.setText(_translate("MainWindow", "IAEA-Th:         "))
        self.pushButton_11.setText(_translate("MainWindow", "Browse.."))
        self.label_9.setText(_translate("MainWindow", "IAEA-K:           "))
        self.pushButton_12.setText(_translate("MainWindow", "Browse.."))
        self.label_10.setText(_translate("MainWindow", "Other:             "))
        self.pushButton_13.setText(_translate("MainWindow", "Browse.."))
        self.label_6.setText(_translate("MainWindow", "Choose a profile to validate:"))
        self.groupBox.setTitle(_translate("MainWindow", "Each Profile contains a set of peaks of interest to be calibrated against"))
        self.pushButton_7.setText(_translate("MainWindow", "Add.."))
        self.label_11.setText(_translate("MainWindow", "Energy Validation Control"))
        self.label_12.setText(_translate("MainWindow", "Isotope:"))
        self.validation_isotope_dropdown.setItemText(0, _translate("MainWindow", "Choose.."))
        self.analyze_button.setText(_translate("MainWindow", "Analyze"))
        self.del_peak_button.setText(_translate("MainWindow", "Delete Peak"))
        self.save_profile_button.setText(_translate("MainWindow", "Save Profile"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Visual Analysis"))
        self.add_peak_button.setText(_translate("MainWindow", "Add Peak"))
        self.label_17.setText(_translate("MainWindow", "Name Of Isotope:"))
        self.label_18.setText(_translate("MainWindow", "Energy(keV):"))
        self.label_25.setText(_translate("MainWindow", "limit HE Rpic:"))
        self.label_26.setText(_translate("MainWindow", "limit BE Rpic:"))
        self.label_27.setText(_translate("MainWindow", "nb canaux BFBE:"))
        self.label_28.setText(_translate("MainWindow", "nb canaux BFHE:"))
        self.label_29.setText(_translate("MainWindow", "larger region peak:"))
        self.label_31.setText(_translate("MainWindow", "Reference width:"))
        self.label_30.setText(_translate("MainWindow", "Range of channels:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Add Peak to Profile"))
        self.back.setText(_translate("MainWindow", "Back"))
        self.groupBox_2.setTitle(_translate("MainWindow", "BFBE"))
        self.label_13.setText(_translate("MainWindow", "Total hits: "))
        self.total_hits_bfbe.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "Hits per channel: "))
        self.hits_per_channel_bfbe.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_3.setTitle(_translate("MainWindow", "BFHE"))
        self.label_19.setText(_translate("MainWindow", "Total hits: "))
        self.total_hits_bfhe.setText(_translate("MainWindow", "TextLabel"))
        self.label_21.setText(_translate("MainWindow", "Hits per channel: "))
        self.hits_per_channel_bfhe.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Region"))
        self.label_14.setText(_translate("MainWindow", "Total hits: "))
        self.total_hits_roi.setText(_translate("MainWindow", "TextLabel"))
        self.label_16.setText(_translate("MainWindow", "Channels inside peak:"))
        self.num_channels_peak.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Pic"))
        self.label_22.setText(_translate("MainWindow", "Total hits: "))
        self.total_hits_pic.setText(_translate("MainWindow", "TextLabel"))
        self.label_24.setText(_translate("MainWindow", "Channels inside peak:"))
        self.num_channels_peak_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_37.setText(_translate("MainWindow", "FWHM(keV)"))
        self.label_35.setText(_translate("MainWindow", "Peak at energy(keV):"))
        self.label_33.setText(_translate("MainWindow", "Peak at channel:"))
        self.fwhm.setText(_translate("MainWindow", "TextLabel"))
        self.channel_peak.setText(_translate("MainWindow", "TextLabel"))
        self.energy_peak.setText(_translate("MainWindow", "TextLabel"))
        self.pa_prev.setText(_translate("MainWindow", "Previous"))
        self.pa_next.setText(_translate("MainWindow", "Next"))
        self.menuOpen.setTitle(_translate("MainWindow", "File"))
        self.menuChart_Design.setTitle(_translate("MainWindow", "Chart Design"))
        self.menuCalibration.setTitle(_translate("MainWindow", "Calibration"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionRun.setText(_translate("MainWindow", "Run"))
